
livecheck:
  db:
    driverclassname: org.sqlite.JDBC
    url: jdbc:sqlite:memory:myDb?cache=shared
    username: sa
    password: sa
hibernate:
  dialect: com.baeldung.dialect.SQLiteDialect
  show_sql: true
  hbm2ddl:
    auto: create-drop