livecheck:
  db:
    driverclassname: org.sqlite.JDBC
    url: jdbc:sqlite:memory:myDb?cache=shared
    user: sa
    password: sa
spring:
  jpa:
    properties:
      hibernate:
        dialect: bar.barinade.livecheck.config.SQLiteDialect
        show_sql: true
        hbm2ddl:
          auto: create-drop
          
discord:
  token: