spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
  datasource:
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/livecheck
          
discord:
  token: